.TH Z_JAIL 1 "2026-06-04" "Z-Jail/v1" "User Commands"
.SH NAME
z_jail \- multi-layer sandbox for native code execution
.SH SYNOPSIS
.B z_jail
\fB\-\-root\fR=\fIpath\fR [\fB\-\-seccomp\-enforce\fR] [\fB\-\-self\-hash=\fIhex\fR]
[\fB\-\-quiet\fR] [\fB\-\-verbose\fR] \fB\-\-\fR \fIprogram\fR [\fIargs...\fR]
.SH DESCRIPTION
Z-Jail applies 7 defence-in-depth layers.
.SH OPTIONS
\fB\-\-root\fR=\fIpath\fR       sandbox root filesystem
\fB\-\-seccomp\-enforce\fR     enable seccomp-BPF whitelist
\fB\-\-self\-hash=\fIhex\fR     verify binary integrity
\fB\-\-quiet\fR               suppress audit output
\fB\-\-verbose\fR             enable debug logging
\fB\-\-version\fR             show build ID
\fB\-\-help\fR                show usage
