name: build
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: make
    - run: make -C tests setup
    - run: bash tests/run_tests.sh
