name: release
on:
  push:
    tags: ['v*']
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: make dist
    - uses: softprops/action-gh-release@v1
      with:
        files: _dist/*.tar.gz
